apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}