name: CD Build
env:
  REPOSITORY: k8serviceaccount
  IMAGE: k8-rebuild-file-drop
  TAG: main

on:
  push:
    branches: 
      - main
      - add_cd

jobs:
  build-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      with:
        submodules: true
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: k8serviceaccount
        password: ${{ secrets.K8DOCKERSECRET }}
    - name: Build and Push Docker Image
      run: |
        docker build app -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA::7} -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-latest -f app/Dockerfile
        docker push ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-latest
        docker push ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA::7}
    - name: Install yq - portable yaml processor
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    - name: Checkout k8-rebuild
      uses: actions/checkout@v2
      with:
        repository: k8-proxy/k8-rebuild
        token: ${{ secrets.K8GITHUBTOKEN }}
        path: k8-rebuild
        ref: main
    - name: Update image tag in k8-rebuild repo
      run: |
        cd k8-rebuild
        IMAGE_TAG=${{ env.TAG }}-${GITHUB_SHA::7}
        git fetch
        git config user.email github-actions@github.com
        git config user.name github-actions
        git checkout -b $IMAGE_TAG origin/${{ env.TAG }}
        # update imagestore selected tag value in the values.yaml file
        yq write kubernetes/values.yaml sow-rest-ui.image.tag $IMAGE_TAG -i
        git add kubernetes/values.yaml
        git commit -m 'update image tag'
        git push origin $IMAGE_TAG

        # create a pull request from a new branch to target branch, merge the PR and delete the source branch.
        gh pr create --base ${{ env.TAG }} --title "Update ${{ env.IMAGESTORESELECTOR }} image tag to $IMAGE_TAG" --body ""
        sleep 5s
        gh pr merge $IMAGE_TAG -s
        git push origin --delete $IMAGE_TAG
        
      env:
        GITHUB_TOKEN: ${{ secrets.K8GITHUBTOKEN }}